module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  roots: ['<rootDir>'],
  testMatch: ['**/?(*.)+(spec|test).[tj]s?(x)'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/main.tsx',
    '!src/vite-env.d.ts',
    '!src/**/*.stories.tsx',
    '!src/types/**',
    '!src/assets/**',
  ],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary', 'cobertura'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.css$': '<rootDir>/src/__mocks__/styleMock.js',
    '^@schemas/(.*)$': '<rootDir>/../synckuropos_schemas/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: {
        target: 'ES2022',
        lib: ['ES2022', 'DOM', 'DOM.Iterable'],
        module: 'ES2022',
        jsx: 'react-jsx',
        esModuleInterop: true,
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        verbatimModuleSyntax: false,
        baseUrl: '.',
        types: ['jest', '@testing-library/jest-dom'],
        paths: {
          '@/*': ['src/*'],
          '@/components/*': ['src/components/*'],
          '@/shared/*': ['src/shared/*'],
          '@/features/*': ['src/features/*'],
          '@/hooks/*': ['src/hooks/*'],
          '@/utils/*': ['src/utils/*'],
          '@/types/*': ['src/types/*'],
          '@/styles/*': ['src/styles/*'],
          '@/db/*': ['src/db/*'],
          '@/assets/*': ['src/assets/*'],
          '@/contexts/*': ['src/contexts/*'],
          '@/helpers/*': ['src/helpers/*'],
          '@schemas/*': ['../synckuropos_schemas/*'],
        },
      },
      useESM: true,
    }],
  },
};
