sonar.projectKey=synckuropos_app
sonar.organization=dr00p3r
sonar.sourceEncoding=UTF-8

# 1. Base y Sources (Analiza todo para bugs)
sonar.projectBaseDir=synckuropos_app
sonar.sources=src
sonar.tests=src

# 2. Definición de Tests
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.ts

# 3. EXCLUSIONES DE COBERTURA (La lista negra masiva)
# Aquí usamos "**/*" para matar carpetas enteras.
sonar.coverage.exclusions=\
  src/features/**/*,\
  src/layouts/**/*,\
  src/components/**/*,\
  src/assets/**/*,\
  src/config/**/*,\
  src/db/**/*,\
  src/lib/**/*,\
  src/styles/**/*,\
  src/types/**/*,\
  src/utils/**/*,\
  src/App.tsx,\
  src/main.tsx,\
  src/vite-env.d.ts

# Nota: Al excluir todo lo anterior, lo único que queda "vivo" para coverage es src/hooks

# 4. Reporte
sonar.javascript.lcov.reportPaths=coverage/lcov.info