sonar.projectKey=synckuropos_app
sonar.organization=dr00p3r
sonar.sourceEncoding=UTF-8

# 1. Base y Sources (Analiza todo para bugs)
sonar.projectBaseDir=synckuropos_app
sonar.sources=src
sonar.tests=src

# 2. Definición de Tests
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.ts

sonar.coverage.exclusions=\
  src/features/**/*,\
  src/layouts/**/*,\
  src/components/**/*,\
  src/assets/**/*,\
  src/config/**/*,\
  src/db/**/*,\
  src/pages/**/*,\
  src/services/**/*,\
  src/__mocks__/**/*,\
  src/workers/**/*,\
  src/lib/**/*,\
  src/styles/**/*,\
  src/types/**/*,\
  src/utils/**/*,\
  src/App.tsx,\
  src/main.tsx,\
  src/hooks/useTelemetry.ts,\
  src/hooks/useCart.tsx,\
  src/vite-env.d.ts,\
  src/setupTests.ts

# 4. Reporte
sonar.javascript.lcov.reportPaths=coverage/lcov.info